// examples/svelte/src/message-bubble.svelte
<script lang='ts'>
  import type { Chat, UIMessageToolCallPart } from '@xsai-use/svelte'

  interface Props {
    message: Chat['message']
    error: Chat['error']
    isError: Chat['isError']
    reload: Chat['reload']
  }
  const { message, error, isError, reload }: Props = $props()
</script>

{#snippet UIMessageTextPart(part)}
  <div>
    {part.text}
  </div>
{/snippet}

{#snippet UIMessageToolResult(part: UIMessageToolCallPart)}
  {#if part.status === 'error' && part.error}
    <pre>
      {String(part.error)}
    </pre>
  {/if}

  {#if part.status === 'complete' && part.result}
    {@const result = part.result}
    {#if typeof result === 'string'}
      <pre>{result}</pre>
    {/if}

    {#if Array.isArray(result)}
      <div>
        {#each result as item}
          <li>
            {#if item.type === 'text'}
              <div>{item.text}</div>
            {/if}
            {#if item.type === 'image_url'}
              <img src={item.image_url.url} alt='Tool Result' style='max-width: 100%; border-radius: 4px;' />
            {/if}
            {#if item.type === 'input_audio'}
              <audio controls>
                <source src={item.input_audio.data} type={`audio/${item.input_audio.format}`} />
                Your browser does not support the audio element.
              </audio>
            {/if}
          </li>
        {/each}
      </div>
    {/if}
  {/if}

{/snippet}

{#snippet UIMessageToolPart(part)}
  {@const hasResult = part.status === 'complete' || part.status === 'error'}
  {@const isLoading = part.status === 'loading' || part.status === 'partial'}
  <div
    class="collapse collapse-arrow border {part.status === 'error' ? 'bg-red-100' : 'bg-base-100'}"
  >
    <input type='checkbox' class='tweak-collapse' />
    <div class='collapse-title font-semibold tweak-collapse tweak-collapse-title-arrow'>{part.toolCall.function.name}</div>
    <div class='collapse-content'>
      {#if isLoading}
        <div class='skeleton h-4 w-full'></div>
      {/if}
      {#if hasResult}
        <div>
          {@render UIMessageToolResult(part)}
        </div>
      {/if}
    </div>
  </div>
{/snippet}

{#snippet UIMessageUnknownPart(part)}
  <div>
    Unknown message part type: {part.type}
  </div>
{/snippet}

{#snippet renderMessageParts(message)}
  {#each message.parts as part, index (index)}
    {#if part.type === 'text'}
      {@render UIMessageTextPart(part)}
    {:else if part.type === 'tool-call'}
      {@render UIMessageToolPart(part)}
    {:else}
      {@render UIMessageUnknownPart(part)}
    {/if}
  {/each}
{/snippet}

{#if message.role === 'system'}
  <div class='flex justify-center'>
    <div class='badge badge-ghost'>
      {@render renderMessageParts(message)}
    </div>
  </div>
{:else}
  <div class="chat {message.role === 'user' ? 'chat-end' : 'chat-start'}">
    <div class="chat-bubble {message.role === 'user' ? 'chat-bubble-primary' : ''}">
      {@render renderMessageParts(message)}
      {#if isError}
        <div class='error-message'>
          ❌
          {error?.message}
        </div>
      {/if}
    </div>
    {#if message.role === 'user'}
      <div class='chat-footer opacity-50'>
        <button type='button' class='link' onclick={() => reload?.(message.id)}>reload from here</button>
      </div>
    {/if}
  </div>
{/if}

<style>
.chat-bubble {
  display: flex;
  flex-direction: column;
  gap: .5rem;
}

.error-message {
  font-size: 12px;
}

.tweak-collapse {
  padding-top: .5rem;
  padding-bottom: .5rem;
  min-height: 2.75rem;
}

.tweak-collapse-title-arrow:after {
  top: 1.4rem;
}
</style>

// examples/vue/src/MessageBubble.vue
<script setup lang="ts">
import type { UIMessage } from '@xsai-use/vue'

interface Props {
  message: UIMessage
  isError?: boolean
  error?: Error | null
  reload?: (id: string) => void | Promise<void>
}

const props = withDefaults(defineProps<Props>(), {
  isError: false,
  error: null
})

// Helper function to check if part is a tool call
const isToolCallPart = (part: any): part is any => {
  return part.type === 'tool-call'
}

// Helper function to safely get tool call properties
const getToolCallPart = (part: any) => {
  return isToolCallPart(part) ? part : null
}
</script>

<template>
  <div v-if="props.message.role === 'system'" class="flex justify-center">
    <div class="badge badge-ghost">
      <div v-for="(part, index) in props.message.parts" :key="index">
        <div v-if="part.type === 'text'">
          {{ part.text }}
        </div>
        <div v-else>
          Unknown message part type: {{ part.type }}
        </div>
      </div>
    </div>
  </div>

  <div v-else :class="['chat', props.message.role === 'user' ? 'chat-end' : 'chat-start']">
    <div :class="[
      'chat-bubble',
      props.message.role === 'user' ? 'chat-bubble-primary' : ''
    ]">
      <div v-for="(part, index) in props.message.parts" :key="index">
        <!-- Text Part -->
        <div v-if="part.type === 'text'">
          {{ part.text }}
        </div>

        <!-- Tool Call Part -->
        <div
          v-else-if="part.type === 'tool-call'"
          :class="[
            'collapse',
            'collapse-arrow',
            'border',
            getToolCallPart(part)?.status === 'error' ? 'bg-red-100' : 'bg-base-100'
          ]"
        >
          <input type="checkbox" class="tweak-collapse" />
          <div class="collapse-title font-semibold tweak-collapse-title-arrow tweak-collapse">
            {{ getToolCallPart(part)?.toolCall?.function?.name }}
          </div>
          <div class="collapse-content">
            <!-- Loading State -->
            <div
              v-if="getToolCallPart(part)?.status === 'loading' || getToolCallPart(part)?.status === 'partial'"
              class="skeleton h-4 w-full"
            ></div>

            <!-- Result State -->
            <div v-if="getToolCallPart(part)?.status === 'complete' || getToolCallPart(part)?.status === 'error'">
              <!-- Error Result -->
              <pre v-if="getToolCallPart(part)?.status === 'error' && getToolCallPart(part)?.error">{{ String(getToolCallPart(part)?.error) }}</pre>

              <!-- Success Result -->
              <template v-if="getToolCallPart(part)?.status === 'complete' && getToolCallPart(part)?.result">
                <!-- String Result -->
                <pre v-if="typeof getToolCallPart(part)?.result === 'string'">{{ getToolCallPart(part)?.result }}</pre>

                <!-- Array Result -->
                <div v-else-if="Array.isArray(getToolCallPart(part)?.result)">
                  <div v-for="(item, itemIndex) in getToolCallPart(part)?.result" :key="itemIndex">
                    <div v-if="typeof item === 'object' && item?.type === 'text'">
                      {{ String(item) }}
                    </div>
                    <img
                      v-else-if="typeof item === 'object' && item?.type === 'image_url'"
                      :src="String(item?.image_url)"
                      alt="Tool Result"
                      style="max-width: 100%; border-radius: 4px;"
                    />
                    <audio
                      v-else-if="typeof item === 'object' && item?.type === 'input_audio'"
                      controls
                    >
                      <source :src="item?.input_audio?.data" :type="`audio/${item?.input_audio?.format}`" />
                      Your browser does not support the audio element.
                    </audio>
                    <div v-else>{{ String(item) }}</div>
                  </div>
                </div>

                <!-- Other Result Types -->
                <div v-else>{{ String(getToolCallPart(part)?.result) }}</div>
              </template>
            </div>
          </div>
        </div>

        <!-- Unknown Part -->
        <div v-else>
          Unknown message part type: {{ part.type }}
        </div>
      </div>

      <!-- Error Message -->
      <div v-if="props.isError" class="error-message">
        ❌ {{ props.error?.message }}
      </div>
    </div>

    <!-- Reload Button for User Messages -->
    <div v-if="props.message.role === 'user'" class="chat-footer opacity-50">
      <button
        type="button"
        class="link"
        @click="props.reload?.(props.message.id)"
      >
        reload from here
      </button>
    </div>
  </div>
</template>
