// examples/vue/src/App.vue
<script setup lang="ts">
import { useChat } from '@xsai-use/vue'
import { tool } from '@xsai/tool'
import { description, object, pipe, string } from 'valibot'
import { ref, onMounted, nextTick, watch } from 'vue'

import MessageBubble from './MessageBubble.vue'

interface ToolMap {
  [key: string]: Awaited<ReturnType<typeof tool>>
}

const inputRef = ref<HTMLInputElement | null>(null)
const isLoadingTools = ref(true)
const loadedTools = ref<ToolMap>({})

// Load tools on component mount
onMounted(async () => {
  isLoadingTools.value = true
  // manually delay loading tools to simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1000))

  try {
    const weatherTool = await tool({
      description: 'Get the weather in a location',
      execute: async ({ location }) => {
        // manually delay loading tools to simulate network delay
        await new Promise(resolve => setTimeout(resolve, 2000))
        if (Math.random() > 0.5) {
          throw new Error('Weather API error')
        }
        return {
          location,
          temperature: 10,
        }
      },
      name: 'weather',
      parameters: object({
        location: pipe(
          string(),
          description('The location to get the weather for')
        ),
      }),
    })

    const calculatorTool = await tool({
      description: 'Calculate mathematical expression',
      execute: ({ expression }) => ({
        // eslint-disable-next-line no-eval
        result: eval(expression),
      }),
      name: 'calculator',
      parameters: object({
        expression: pipe(
          string(),
          description('The mathematical expression to calculate')
        ),
      }),
    })

    loadedTools.value = {
      weather: weatherTool,
      calculator: calculatorTool,
    }
  } catch (err) {
    console.error('Error loading tools:', err)
  } finally {
    isLoadingTools.value = false
  }
})

const {
  handleSubmit,
  handleInputChange,
  input,
  messages,
  status,
  error,
  reset,
  stop,
  reload,
} = useChat({
  id: 'simple-chat',
  preventDefault: true,
  initialMessages: [
    {
      role: 'system',
      content: 'you are a helpful assistant.',
    },
  ],
  baseURL: 'http://localhost:11434/v1/',
  model: 'mistral-nemo-instruct-2407',
  maxSteps: 3,
  toolChoice: 'auto',
  tools: Object.values(loadedTools.value),
})

// Handle send button click based on status
const handleSendButtonClick = (e: Event) => {
  if (status.value === 'loading') {
    e.preventDefault()
    stop()
  }
  // Let the form submission handle other cases
}

// Focus input when status changes to idle
watch(status, (newStatus) => {
  if (newStatus === 'idle' && inputRef.value) {
    nextTick(() => {
      inputRef.value?.focus()
    })
  }
})
</script>

<template>
  <div style="display: flex; justify-content: center; padding: 20px;">
    <div class="useChat-container">
      <div class="useChat-header">
        <h2>useChat</h2>
      </div>

      <div class="chat-tools-section">
        <div class="tools-container">
          <span>Available tools:</span>
          <span v-if="isLoadingTools" class="loading loading-infinity loading-md"></span>
          <template v-else>
            <div
              v-for="toolName in Object.keys(loadedTools)"
              :key="toolName"
              class="tool-badge"
            >
              <span class="tool-icon">🔧</span>
              <span class="tool-name">{{ toolName }}</span>
            </div>
          </template>
        </div>
      </div>

      <div class="messages-container">
        <MessageBubble
          v-for="(message, idx) in messages"
          :key="message?.id || idx"
          :message="message"
          :isError="idx === messages.length - 1 && status === 'error'"
          :error="idx === messages.length - 1 ? error : null"
          :reload="reload"
        />
      </div>

      <form @submit="handleSubmit" class="input-container">
        <div class="join" style="width: 100%;">
          <input
            ref="inputRef"
            type="text"
            class="input join-item"
            placeholder="say something..."
            style="width: 100%;"
            :value="input"
            @input="handleInputChange"
            :disabled="status !== 'idle'"
          />
          <button
            class="btn join-item"
            @click="handleSendButtonClick"
            :type="status === 'loading' ? 'button' : 'submit'"
          >
            {{ status === 'loading' ? 'Stop' : 'Send' }}
          </button>
          <button
            class="btn join-item"
            @click="(e) => {
              e.preventDefault()
              reset()
            }"
            type="button"
          >
            <span v-if="status === 'loading'" class="loading loading-dots loading-md"></span>
            <span v-else>Reset</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// examples/react/src/app.tsx
import { useChat } from '@xsai-use/react'
import { tool } from '@xsai/tool'

import classNames from 'classnames'
import { useEffect, useRef, useState } from 'react'

import { description, object, pipe, string } from 'valibot'

import {
  UIMessageTextPart,
  UIMessageToolPart,
  UIMessageUnknownPart,
} from './ui-message-part'

// Inline styles for the component
const styles = {
  chatBubble: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '.5rem',
  },
  chatHeader: {
    backgroundColor: '#f0f2f5',
    borderBottom: '1px solid #ddd',
    padding: '10px 15px',
    textAlign: 'center' as const,
  },
  chatContainer: {
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    flexDirection: 'column' as const,
    fontFamily: 'Arial, sans-serif',
    height: '90vh',
    overflow: 'hidden',
    width: '600px',
  },
  inputContainer: {
    backgroundColor: '#f0f2f5',
    borderTop: '1px solid #ddd',
    display: 'flex',
    padding: '10px',
    width: '100%',
  },
  messagesContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column' as const,
    gap: '10px',
    overflowY: 'auto' as const,
    padding: '15px',
  },
  errorMessage: {
    fontSize: '12px',
  },
  toolsContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '8px',
    minHeight: 'fit-content',
  },
  toolBadge: {
    backgroundColor: '#e9ecef',
    borderRadius: '16px',
    padding: '6px 12px',
    fontSize: '13px',
    color: '#495057',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    border: '1px solid #dee2e6',
  },
  toolIcon: {
    color: '#495057',
    fontSize: '14px',
  },
  toolName: {
    fontSize: '13px',
    color: '#495057',
  },
  chatToolsSection: {
    padding: '10px',
    alignContent: 'center',
    flexShrink: 0,
    borderBottom: '1px solid #ddd',
    backgroundColor: '#f8f9fa',
  },
}

interface ToolMap {
  [key: string]: Awaited<ReturnType<typeof tool>>
}

function ChatMessage({
  message,
  isError = false,
  error,
}: {
  message: ReturnType<typeof useChat>['messages'][number]
  isError?: boolean
  error?: Error | null
}) {
  return (
    <div className={
      classNames(
        'chat',
        message.role === 'user' ? 'chat-end' : 'chat-start',
      )
    }
    >
      <div
        className={
          classNames(
            'chat-bubble',
            message.role === 'user' ? 'chat-bubble-primary' : '',
          )
        }
        style={{ ...styles.chatBubble }}
      >
        {message.parts.map((part, index) => {
          switch (part.type) {
            case 'text':
              return <UIMessageTextPart key={index} text={part.text} />
            case 'tool-call':
              return <UIMessageToolPart key={part.toolCall.id} part={part} />
            case 'audio':
            case 'image':
            case 'reasoning':
            case 'refusal':
            default:
              return <UIMessageUnknownPart key={index} type={part.type} />
          }
        })}
        {isError && (
          <div style={styles.errorMessage}>
            {error?.message}
          </div>
        )}
      </div>
    </div>
  )
}

// Simple Chat Component implementation
export function ChatComponent() {
  const inputRef = useRef<HTMLInputElement>(null)
  const [isLoadingTools, setIsLoadingTools] = useState(true)
  const [loadedTools, setLoadedTools] = useState<ToolMap>({})

  // Load tools on component mount
  useEffect(() => {
    const loadTools = async () => {
      setIsLoadingTools(true)
      await new Promise(resolve => setTimeout(resolve, 1000))
      try {
        const weatherTool = await tool({
          description: 'Get the weather in a location',
          execute: async ({ location }) => {
            await new Promise(resolve => setTimeout(resolve, 2000))
            if (Math.random() > 0.5) {
              throw new Error('Weather API error')
            }
            return {
              location,
              temperature: 10,
            }
          },
          name: 'weather',
          parameters: object({
            location: pipe(
              string(),
              description('The location to get the weather for'),
            ),
          }),
        })

        const calculatorTool = await tool({
          description: 'Calculate mathematical expression',
          execute: ({ expression }) => ({
            // eslint-disable-next-line no-eval, ts/no-unsafe-assignment
            result: eval(expression),
          }),
          name: 'calculator',
          parameters: object({
            expression: pipe(
              string(),
              description('The mathematical expression to calculate'),
            ),
          }),
        })

        setLoadedTools({
          weather: weatherTool,
          calculator: calculatorTool,
        })
      }
      catch (err) {
        console.error('Error loading tools:', err)
      }
      finally {
        setIsLoadingTools(false)
      }
    }

    // eslint-disable-next-line ts/no-floating-promises
    loadTools()
  }, [])

  const {
    handleSubmit,
    handleInputChange,
    input,
    messages,
    status,
    error,
    reset,
    stop,
  } = useChat({
    id: 'simple-chat',
    preventDefault: true,
    initialMessages: [
      {
        role: 'system',
        content: 'you are a helpful assistant.',
      },
    ],
    baseURL: 'http://localhost:11434/v1/',
    model: 'mistral-nemo-instruct-2407',
    maxSteps: 3,
    toolChoice: 'auto',
    tools: Object.values(loadedTools),
  })

  // Handle send button click based on status
  const handleSendButtonClick = (e: React.MouseEvent) => {
    if (status === 'loading') {
      e.preventDefault()
      stop()
    }
    else {
      // Let the form submission handle this case
    }
  }

  // Focus input when status changes to idle
  useEffect(() => {
    if (status === 'idle' && inputRef.current) {
      inputRef.current.focus()
    }
  }, [status])

  return (
    <div style={styles.chatContainer}>
      <div style={styles.chatHeader}>
        <h2>useChat</h2>
      </div>

      <div style={styles.chatToolsSection}>
        <div style={styles.toolsContainer}>
          <span>Available tools:</span>
          {
            isLoadingTools
              ? <span className="loading loading-infinity loading-md"></span>
              : Object.keys(loadedTools).map(toolName => (
                  <div key={toolName} style={styles.toolBadge}>
                    <span style={styles.toolIcon}>🔧</span>
                    <span style={styles.toolName}>{toolName}</span>
                  </div>
                ))
          }
        </div>
      </div>

      <div style={styles.messagesContainer}>
        {/* eslint-disable-next-line ts/strict-boolean-expressions */}
        {messages.map((message, idx) => message
          ? (
              <ChatMessage
                key={message.id}
                message={message}
                isError={idx === messages.length - 1 && status === 'error'}
                error={idx === messages.length - 1 ? error : null}
              />
            )
          : 'null')}
      </div>

      {/* eslint-disable-next-line ts/no-misused-promises */}
      <form data-test-id="form" onSubmit={handleSubmit} style={styles.inputContainer}>
        <div className="join" style={{ width: '100%' }}>
          <input
            type="text"
            className="input join-item"
            placeholder="say something..."
            style={{ width: '100%' }}
            onChange={handleInputChange}
            value={input}
            disabled={status !== 'idle'}
            ref={inputRef}
          />
          <button
            className="btn join-item"
            onClick={handleSendButtonClick}
            type={status === 'loading' ? 'button' : 'submit'}
          >
            {status === 'loading'
              ? <span className="loading loading-dots loading-md"></span>
              : 'Send'}
          </button>
          <button
            className="btn join-item"
            onClick={(e) => {
              e.preventDefault()
              reset()
            }}
            type="button"
          >
            Reset
          </button>
        </div>
      </form>
    </div>
  )
}

// Usage example
export function App() {
  return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: '20px' }}>
      <ChatComponent />
    </div>
  )
}
